; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "FlaUI-MCP"
#define MyAppPublisher "Dennis Hempel"
#define MyAppURL "https://skoosoft.de"
#define MyAppExeName "FlaUI.MCP.exe"
#define MyAppSourceFolder "bin\Publish"
#define ApplicationVersion GetFileVersion(MyAppSourceFolder + '\' + MyAppExeName)

[Setup]
AppId={{C3884566-0E85-449E-9366-F03E43505693}
VersionInfoVersion={#ApplicationVersion}
AppName={#MyAppName}
AppVersion={#ApplicationVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=c:\programdata\{#MyAppName}
DisableProgramGroupPage=yes
SetupLogging=yes
OutputDir=bin
OutputBaseFilename={#MyAppName}.Setup
Compression=lzma2/normal
SolidCompression=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
PrivilegesRequired=admin
CloseApplications=force
RestartApplications=yes

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Files]
Source: "{#MyAppSourceFolder}\*"; Excludes: "appsettings.json"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs;

[InstallDelete]
;Type: files; Name: "{app}\*.dll";

[Dirs]
Name: "{app}"; Permissions: users-full

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "-install -silent";

[UninstallRun]
Filename: "{app}\{#MyAppExeName}"; Parameters: "-uninstall -silent";

[Code]
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin 
      if MsgBox('Sollen alle Programm-Einstellungen gelöscht werden?', mbConfirmation, MB_YESNO) = IDYES
      then
        begin
          DelTree(ExpandConstant('{app}'), True, True, True);
        end;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
    Exec('cmd', '/C net stop FlaUI-MCP', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure StopService();
var
  ResultCode: Integer;
begin
    Exec('cmd', '/C net stop FlaUI-MCP', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;  
    
procedure StartService();
var
  ResultCode: Integer;
begin
    Exec('cmd', '/C net start FlaUI-MCP', '', SW_HIDE, ewNoWait, ResultCode);
end;
